# name: automerge
# permissions:
#   contents: write
# env:
#   MERGE_LABELS: ""
#   MAIN_BRANCH: "main"
# on:
#   pull_request_target:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
# jobs:
#   automerge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
      
#       - name: Merge Pull Request
#         run: |
#           PR_BRANCH="${{ github.event.pull_request.head.ref }}"
#           git checkout "${MAIN_BRANCH}"
#           git pull origin "${MAIN_BRANCH}"
#           git merge --no-ff "${PR_BRANCH}" -m "Merge PR #${{ github.event.pull_request.number }}"

#       - name: Push changes
#         run: |
#           git push origin "${MAIN_BRANCH}"
